# environment.yml
name: aurora
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'digitalglobe'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::python=3.6.6
- conda-forge::pip<10
- conda-forge::numpy>=1.15.4,<1.16
- conda-forge::pandas>=0.23.4,<0.24
- conda-forge::boto3>=1.9.90,<2.0
- conda-forge::tqdm>=4.30,<5.0
- conda-forge::click
- pip:
  - awscli>=1.16.100,<2.0